# Generated by Django 5.2.5 on 2025-09-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ribbit',
            name='likes_count',
        ),
    ]
