# Generated by Django 5.2.5 on 2025-09-22 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0003_remove_ribbit_likes_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commnets', to=settings.AUTH_USER_MODEL)),
                ('ribbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commnets', to='ribbits.ribbit')),
            ],
        ),
    ]
