# Generated by Django 5.2.5 on 2025-09-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0005_rename_commnet_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
