# Generated by Django 5.2.5 on 2025-09-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0007_alter_comment_author_alter_comment_ribbit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ribbitmedia',
            name='text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
