# Generated by Django 5.2.5 on 2025-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0008_ribbitmedia_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ribbit',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='ribbit_media/'),
        ),
        migrations.AddField(
            model_name='ribbit',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='RibbitMedia',
        ),
    ]
