# Generated by Django 5.2.5 on 2025-10-01 15:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0011_alter_ribbit_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ribbit',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
