# Generated by Django 4.2.26 on 2025-11-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbits', '0014_emailpreferences_emailqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailpreferences',
            name='email_on_new_post_from_following',
            field=models.BooleanField(default=True),
        ),
    ]
