# Generated by Django 5.2.5 on 2025-09-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
