# Generated by Django 5.2.5 on 2025-10-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_created_at'),
    ]

    operations = [
    ]
