# Generated by Django 5.2.5 on 2025-11-09 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 8, 13, 14, 597269, tzinfo=datetime.timezone.utc)),
        ),
    ]
