# Generated by Django 4.2.28 on 2026-04-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='is_verfied',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='join_date',
        ),
    ]
